### ISSUE TITLE
[FEAT] 获取当前用户的基本信息

### ISSUE THREAD

**Issue by xiaolfeng** [fantastic-editor/FantasticEditorApi#8]
### 功能点名称

获取当前用户信息

### 功能描述详情

根据前端传递的 uuid 参数进行查询，其查询结果包含用户的基本信息，角色组信息，权限信息，付费会员信息，以及个人其他信息。其信息需要存储进入 redis 进行存储。

### Apifox接口名称

用户控制器/获取当前用户信息

**Comment by xiangZr-hhh** [comment]
### **功能点名称**
BOS 配置

**### 功能描述详情**
根据手机号、用户名、邮箱、uuid获取用户公开的信息，用户信息不包括密码等敏感信息

Apifox接口名称
检索用户开放信息
